## Задание 1 ##
**Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.**

In [2]:
import pandas as pd

In [86]:
movies = pd.read_csv('/Users/klavdiakavesnikova/projects/практики к лекциям/10._Основы_pandas/ml-latest-small/movies.csv')
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [190]:
rate = pd.read_csv('/Users/klavdiakavesnikova/projects/практики к лекциям/10._Основы_pandas/ml-latest-small/ratings.csv')
filtered_rate = rate[ rate.rating == 5.0]
need_id = filtered_rate['movieId'].value_counts().head(1)

In [191]:
movies[ movies.movieId == need_id.index[0]].head()

     movieId                             title       genres
277      318  Shawshank Redemption, The (1994)  Crime|Drama

# Задание 2 #
**По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.**

Фильтр получился очень массивным

In [126]:
energy = pd.read_csv('/Users/klavdiakavesnikova/projects/практики к лекциям/10._Основы_pandas/power.csv')

In [145]:
filtered_countries = energy[ ((energy['country']=='Lithuania') | (energy['country']=='Latvia') | (energy['country']=='Estonia')) & (energy['category'].isin([4, 12, 21])) & ((energy['year'] < 2011) | (energy['year'] > 2005))]
filtered_countries.head()

       country  year  quantity  category
10617  Estonia  2008       1.0         4
10618  Estonia  2007       0.0         4
10619  Estonia  2006       0.0         4
10620  Estonia  2005       1.0         4
10621  Estonia  2004       1.0         4

In [146]:
filtered_countries_positive_quantity = filtered_countries[ (filtered_countries['quantity'] >= 0)]
filtered_countries_positive_quantity['quantity'].sum()

970728.0

## Задание 3 ##
**Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
Примеры страниц (необязательно брать именно эти): 
https://fortrader.org/quotes
https://www.finanz.ru/valyuty/v-realnom-vremeni**

In [148]:
page_url = 'https://www.finanz.ru/valyuty/dinamika-valjut'

df = pd.read_html(page_url, attrs = {'class': 'quote_list performance'}, encoding='utf-8')
df[0]

,Рубль,Курс,1 день %,YTD %,1 неделя %,1 месяц %,3 мес. %,6 мес. %,1 год %,3 года %,5 лет %
0,CNY/RUB,100682,"1,84 %",106055,08194,03099,-11672,110454,71279,124131,98001
1,GBP/RUB,880702,"2,26 %",4591,-00995,-0567,-126719,60204,73141,11337,-18799
2,USD/RUB,711385,"1,36 %",124513,09778,-05826,-118823,123767,104463,173846,251778
3,JPY/RUB,06598,"1,36 %",140117,07088,00615,-113994,147485,111649,227702,431195
4,CHF/RUB,751590,"2,13 %",147417,09256,09469,-11507,155774,137582,183267,221022
5,EUR/RUB,799919,"1,41 %",127115,04581,04471,-104975,127974,88226,151008,251481
6,Евро,Курс,1 день %,YTD %,1 неделя %,1 месяц %,3 мес. %,6 мес. %,1 год %,3 года %,5 лет %
7,EUR/CHF,10647,"-0,43 %",-20452,-0328,-03933,03822,-23189,-45069,-27209,23429
8,EUR/USD,11245,"0,03 %",00651,-03507,11127,08854,0434,-14446,-1914,-01068
9,EUR/GBP,09085,"-0,57 %",74751,07036,11403,17586,63971,1377,33995,273957
10,EUR/JPY,1212700,"0,31 %",-13535,-01246,04427,02877,-17042,-21282,-62446,-12662
11,Доллар США,Курс,1 день %,YTD %,1 неделя %,1 месяц %,3 мес. %,6 мес. %,1 год %,3 года %,5 лет %
12,USD/CHF,09467,"-0,49 %",-20209,00369,-14607,-04244,-27956,-29359,-08214,24924
13,USD/JPY,1078530,"0,28 %",-14142,02264,-0603,-05845,-21059,-06905,-4437,-12577
14,USD/GBP,08077,"-0,64 %",74978,10618,00486,08875,59779,29018,54194,275484
15,USD/EUR,08892,"-0,04 %",00401,03877,-1074,-08378,-04055,14929,19988,01422
16,Японская иена,Курс,1 день %,YTD %,1 неделя %,1 месяц %,3 мес. %,6 мес. %,1 год %,3 года %,5 лет %
17,JPY/CHF (100:1),08800,"-0,74 %",-06828,-02347,-08943,01631,-06717,-24468,40376,179093
18,JPY/USD,00093,"-0,28 %",14042,-02501,05831,05645,21272,06671,48326,137817
19,JPY/GBP,00075,"-0,89 %",90072,08091,06321,14571,82323,35883,96043,454365
20,JPY/EUR (100:1),08200,"-0,29 %",14449,01367,-04971,-0278,17132,21699,66103,139123
21,Фунт стерлингов,Курс,1 день %,YTD %,1 неделя %,1 месяц %,3 мес. %,6 мес. %,1 год %,3 года %,5 лет %
22,GBP/CHF,11718,"0,14 %",-88315,-1024,-14494,-12664,-82745,-56627,-59131,-196496
23,GBP/USD,12375,"0,60 %",-68655,-09945,00081,-08235,-55836,-27649,-50973,-215457
24,GBP/JPY,1334861,"0,89 %",-8263,-08026,-06281,-14361,-76062,-3464,-93202,-314435
25,GBP/EUR,11008,"0,58 %",-69392,-06684,-11061,-15928,-61289,-13457,-32721,-214949
26,Швейцарский франк,Курс,1 день %,YTD %,1 неделя %,1 месяц %,3 мес. %,6 мес. %,1 год %,3 года %,5 лет %
27,USD/CHF,09467,"-0,49 %",-20209,00369,-14607,-04244,-27956,-29359,-08214,24924
28,GBP/CHF,11718,"0,14 %",-88315,-1024,-14494,-12664,-82745,-56627,-59131,-196496
29,JPY/CHF (100:1),08800,"-0,74 %",-06828,-02347,-08943,01631,-06717,-24468,40376,179093
30,EUR/CHF,10647,"-0,43 %",-20452,-0328,-03933,03822,-23189,-45069,-27209,23429
31,Украинская гривна,Курс,1 день %,YTD %,1 неделя %,1 месяц %,3 мес. %,6 мес. %,1 год %,3 года %,5 лет %
32,CHF/UAH,282039,"0,39 %",149582,-00782,08148,-43322,168343,49457,30944,239229
33,USD/UAH,266950,"-0,11 %",126451,-00431,-0649,-47533,135804,18737,22565,270231
34,GBP/UAH,330484,"0,52 %",47884,-10932,-06972,-55916,71732,-09991,-29956,-04171
35,EUR/UAH,300225,"-0,07 %",126,-0429,04297,-39487,140425,03983,05191,267891

In [149]:
type(df[0])

pandas.core.frame.DataFrame

In [150]:
currency = pd.read_html('dinamika-valjut', encoding='utf-8')
currency[0]

,0,1,2,3,4,5,6,7,8,9,10,11
0,ММВБ,2 762,"0,0%",Nasdaq,9 757,"-2,6%",Биткойн,9 112,"-0,2%",USD/RUB,698393,"0,1%"
1,РТС,1 247,"-0,8%",S&P500,3 009,"-2,4%",Нефть,401,"-1,4%",EUR/RUB,785999,"0,4%"
2,Dow,25 016,"-2,8%",FTSE100,6 159,"0,2%",Золото,1 772,"0,0%",EUR/USD,11255,"0,3%"

In [151]:
type(currency[0])

pandas.core.frame.DataFrame